### ISSUE TITLE
Release v0.3

### ISSUE THREAD

**Issue by ThibaultMarzullo** [henze-research-group/MODRLC#37]
Preparation for the v0.3 release.

Features:

- [x] Add multi-building simulation, [Issue #35](https://github.com/henze-research-group/MODRLC/issues/29)
- [x] Add support for multiple metamodels per case, [Issue #28](https://github.com/henze-research-group/MODRLC/issues/28)

Documentation:
[Issue #31](https://github.com/henze-research-group/MODRLC/issues/31)
- [ ] Update all README.md files
- [ ] Add Gym documentation
- [ ] Publish the Wiki in place of the PDF manual

Examples:

- [ ] Add tutorials to the Wiki, [Issue #32](https://github.com/henze-research-group/MODRLC/issues/32)
- [ ] Fix the single-zone examples, [Issue #28](https://github.com/henze-research-group/MODRLC/issues/28)
- [ ] Add multi-building MPC
- [ ] Add IAQ MPC
- [ ] Update RL examples, [Issue #34](https://github.com/henze-research-group/MODRLC/issues/34)

Test cases:

- [x] Update SOM3 to support CO2 contaminant modelling and sensing, [Issue #30 ](https://github.com/henze-research-group/MODRLC/issues/30)
- [ ] Add variations of the SOM3 model for multi-building and for RL transfer learning
